apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-automatch-inventory-bs-configmap
  namespace: automatch
data:
  NODE_ENV: "production"
  PORT: "3000"
  DATABASE_URL: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-automatch-inventory-bs-deploy
  namespace: automatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-automatch-inventory-bs
  template:
    metadata:
      labels:
        app: ms-automatch-inventory-bs
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ms-automatch-inventory-bs
          image: victor0141/ms-automatch-inventory-bs:1.3
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ms-automatch-inventory-bs-configmap
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ms-automatch-inventory-bs-configmap
                  key: PORT
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ms-automatch-inventory-bs-configmap
                  key: DATABASE_URL
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m" 

---
apiVersion: v1
kind: Service
metadata:
  name: ms-automatch-inventory-bs-svc
  namespace: automatch
spec:
  selector:
    app: ms-automatch-inventory-bs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

